#!/bin/bash
#
# maked - monitor file modification and invoke 'make' automatically
#
#                                                            2011-09-20
#                                     Ryoichi KATO <ryo1kato@gmail.com>
#                                      http://github.com/ryo1kato/maked
#
#   'maked' is a utility to build a source tree automatically using
#   make, or any tool you want, whenever any source file is modified.
#   'maked' uses Linux's inotify-tools package. So you have to install it
#   first:
#
#       $ sudo apt-get install inotify-tools    (On Debian / Ubuntsu etc.)
#     or
#       $ sudo yum install inotify-tools        (On Redhat/Fedora etc.)
#
#   Once started, 'maked' monitors filesystem using inotifywait(1), and
#   whenever change is detected under current working directory, it calls
#   'make' command (or any command specified with '-m' option)
#
#   For performance reasons, 'maked' won't execute 'make' more frequent
#    than once per 2 seconds by default. (in other words, minimum
#   interval to execute 'make' is 2secs) If a change is detected in less
#   than 2 seconds from the previous change, it will scheduled to be
#   executed after 2 seconds. You can change the interval by '-i' option,
#   or specify '0' to disable this feature completely.
#

interval=2
## default is object files, temporary/backup files, dotfiles and core files.
exclude='\.(out|o|obj|a|so|class|hi|hc)$' # object files
exclude="$exclude"'|\.(tmp|orig|old[0-9]*|bak[0-9]*)$|.*~$' # backup files
exclude="$exclude"'|/\..*' # dot file (note for preceding '/')
exclude="$exclude"'|^(out|tmp|core|[0-9]+)$' # coredump etc.
makecmd='make'

#####################################################
progname='maked'
version='v0.1'
copyright='2011, Ryoichi KATO <ryo1kato@gmail.com>'
license="GPLv2: GNU GPL version 2"

print_version () {
cat <<EOF
$progname $version
License $license
Copyright (c) $copyright"
EOF
}

print_defaults () {
    for var in interval exclude makecmd
    do
        eval print '%10s: %s\n' $var \$var
    done
}

print_help () {
cat << EOF
Usage: $progname [OPTSIONS] [--] [MAKE_ARGS...]
  Monitor changes under current directory and runs 'make'
EXAMPLE
  maked -- -j 3
      Run make with -j 3 option when changes are detected.
  maked --interval 10 vmlinux
      Build 'vmlinux' file, with minimum interval 10 seconds.
  maked --cmd ant
      Call 'ant' command instead of 'make'.
OPTIONS
  -i, --interval=SEC   Minimum interval to run make. (default ${interval}sec.)
  -e, --exclude=REGEX  Files to be ignored, as POSIX regular expression.
  (default is object/backup/dot-files such as '.a', '.bak', '.git' etc)
                       If you want to ignore some dir, try '^./YourDirName'
  -E, --add-exclude    Instead of overriding default value of '--exclude',
                       specify additional regex for ignoring files.
  -C, --diretory       Set current directory (default: '.')
                       (Synonymous to make's same option)
  -c, --cmd=COMMAND    Specify alternative make command.
  -v, --verbose        Print detail information.
  -V, --version        Print version information.
  -h, --help           Show this help.
  --                   Indicate end of option for maked, in case
                       MAKE_ARGS starts with dash('-').
BUGS
  * Works only on Linux platform, because it uses inotify(7) systemcalls.
    vi 'inotify-tools' utility.
  * If a directory name matches to a regex specified by '--exclude',
    all changes within the directory is ignored.
EOF
}

print_help_no_inotify_tools () {
cat <<EOF >&2
$progname: inotify-tools is not installed (or not available in the \$PATH)
    To install it, try
        $ sudo yum install inotify-tools      (on Redhat/Fedora etc.)
    or
        $ sudo apt-get install inotify-tools  (on Debian/Ubuntu etc.)
EOF
}

#####################################################
##
## Common Functions
##
MSG () { echo "$progname: $*"; }
DIE () { MSG "ERROR: $@" >&2; exit 1; }
MSG_V () {
    if [ "$opt_verbose" = yes ]; then
        MSG "$@"
    fi
}

#####################################################
##
## Utility Functions
##

# discard all the input(event output) while executing make command
discard_stdin () {

    ## NOTE: Somehow 'read -t 0' this doesn't work with bash (even with bash-4)
    ## works with zsh and AT&T ksh93, though.
    # while read -t 0 line
    # do
    #     MSG_V "Discarding pending event: '$line'"
    # done

    # Use /dev/stdin instead of normal stdin because dd close stdin,
    # which cause subsequent read to fail
    dd iflag=nonblock if=/dev/stdin 2> /dev/null | while read line
    do
        MSG_V "Discarding pending event: $line"
    done
}


#####################################################
##
## Parse Commandline Options
##
optparse () {
    local opt="$1"
    local arg="$2"
    local name="$3"
    case $1 in
        --*=*)
            eval "$name=\"${opt#*=}\"";
            return 0;;
        -*)
            [ -n "$arg" ] || DIE "No argument for option '$opt'; try '--help'"
            eval "$name=\"$arg\"";
            return 1;; # indicates caller must do extra 'shift'
        *) DIE "Internal Error"
    esac
}

while [ $# -ge 1 ]
do
    case $1 in
        -[a-z][a-z]*)
            # expand '-abcd' to '-a -bcd' (and eventually '-a -b -c -d')
            set -- ${1:0:2} -${1:2}; continue;;
        -e|--exclude*)        optparse "$1" "$2" exclude     || shift;;
        -E|--add-exclude*)    optparse "$1" "$2" add_exclude || shift
                              exclude="$exclude|$add_exclude"
                              ;;
        -C|--directory*)      optparse "$1" "$2" directory   || shift;;
        -c|--cmd*|--command*) optparse "$1" "$2" makecmd     || shift;;
        -i|--interval*)       optparse "$1" "$2" interval    || shift;;
        -v|--verbose) opt_verbose=yes;;
        -V|--version) print_version; exit 0;;
        -h|--help)    print_help; exit 0;;
        --) shift; break;;
        -*) DIE "Unknown option $1" ;;
        *)  break;;
    esac
    shift
done

###
### Check Commandline Options
###
if ! [[ $interval =~ ^[0-9]+$ ]];
then
    DIE "Invalid argument for '--interval': $interval"
fi

if [ -d "$directory" -a -x "$directory" ]; then
    cd "$directory"
elif [ -n "$directory" ]; then
    DIE "Cannot change directory into '$directory'"
else
    directory="$PWD"
fi


#####################################################
##
## Start Execution
##
if ! type inotifywait > /dev/null 2>&1
then
    print_help_no_inotify_tools
    exit 1
fi

MSG_V "-------- Started --------"
MSG_V "    interval:  $interval sec"
MSG_V "    command:   $makecmd"
MSG_V "    args:      $*"
MSG_V "    exclude:   $exclude"
MSG_V "    directory: $directory"
MSG_V "-------------------------"


if [ -n "$opt_verbose" ]; then
    inotifywait_opt=''
else
    inotifywait_opt='--quiet'
fi

last_executed=0
inotifywait -m $inotifywait_opt \
    -e create -e modify -e move \
    --exclude "$exclude" \
    -r . |
while read dir event file
do
    MSG_V "Event '$event' for file '$file' in '$dir'"
    if [[ $event =~ ISDIR ]]
    then
        MSG_V "Ignoring change of '$dir'"\
              "(changes for directories are all ignored)"
    ## It's easy to debug not using "inotifywait --exclude"
    #elif [[ $file =~ $exclude ]]
    #then
    #    MSG_V "Ignoring change of '$dir': match to exclude pattern"
    else
        ((remain = (last_executed + interval) - SECONDS))
        if (( remain > 0 ))
        then
            MSG_V "$remain seconds to wait."
            sleep $remain
        fi
        MSG "Executing: '$makecmd'"
        MSG_V "      args: '$*'"
        MSG_V "      file '$file' changed"
        "$makecmd" "$@"
        MSG_V "Command finished."
        last_executed=$SECONDS
        discard_stdin
    fi
done

inotifywait_rc="${PIPESTATUS[0]}"
if [ "$inotifywait_rc" -ne 0 ]; then
    DIE "inotifywait(1) exited abnormally: error code: $inotifywait_rc"
fi
